tap "homebrew/bundle"

brew "chezmoi"
brew "clang-format"
brew "coreutils"
brew "eza"
brew "fzf"
brew "gcc"
brew "gh"
brew "git"
brew "glpk"
brew "gnutls"
brew "gnupg"
brew "iperf3"
brew "lazygit"
brew "lizard-analyzer"
brew "llvm"
brew "make"
brew "mas"
brew "neovim"
brew "openssh"
brew "pyenv"
brew "rclone"
brew "ripgrep"
brew "rust"
brew "stow"
brew "tmux"
brew "tree"
brew "zoxide"

cask "1password"
cask "1password-cli"
cask "86box"
cask "alacritty"
cask "alt-tab"
cask "discord"
cask "docker"
cask "font-meslo-lg-nerd-font"
cask "handbrake"
cask "google-chrome"
cask "heroic"
cask "iina"
cask "iterm2"
cask "keka"
cask "linearmouse"
cask "obsidian"
cask "omnidisksweeper"
cask "openvpn-connect"
cask "oracle-jdk"
cask "raycast"
cask "rectangle"
cask "syncthing"
cask "tower"
cask "transmission"
cask "utm"
cask "visual-studio-code"
cask "whisky"
cask "zed"

mas "Amphetamine", id: 937984704
mas "Goodnotes", id: 1444383602
mas "Microsoft To Do", id: 1274495053
mas "Spark Desktop", id: 6445813049
mas "WhatsApp", id: 310633997
mas "WireGuard", id: 1451685025
mas "Xcode", id: 497799835
