# Colors (Material Darker)

# Default colors
[colors.primary]
background = '0x212121'
foreground = '0xeeffff'

# Cursor colors
[colors.cursor]
text =   '0xffffff'
cursor = '0xffffff'

# Normal colors
[colors.normal]
black =   '0x000000'
red =     '0xff5370'
green =   '0xc3e88d'
yellow =  '0xffcb6b'
blue =    '0x82aaff'
magenta = '0xc792ea'
cyan =    '0x89ddff'
white =   '0xffffff'

# Bright colors
[colors.bright]
black =   '0x545454'
red =     '0xff5370'
green =   '0xc3e88d'
yellow =  '0xffcb6b'
blue =    '0x82aaff'
magenta = '0xc792ea'
cyan =    '0x89ddff'
white =   '0xffffff'
